### ISSUE TITLE
add reverse_each method

### ISSUE THREAD

**Issue by EvandroLG** [EvandroLG/array.lua#9]

**Comment by PhilipRoman** [comment]
Isn't this functionality already available?
```lua
array.map(x, array.reverse)
```

**Comment by EvandroLG** [comment]
Hey @PhilipRoman 

You can get this result with the code above for sure, but it'd be much easer to just call `array.reverse_each`. Another thing is this code has quadratic time and using just one loop we can make the time linear.

What do you think about these two points? Do they make sense to you?

**Comment by PhilipRoman** [comment]
Well, it seems like a bad practice to create functions like `x_each` when we already have `array.map`.

Also, I don't think that the runtime speed can be improved by creating a special function. Can you elaborate on that?

**Comment by EvandroLG** [comment]
I thought in something like this:

```lua
function reverse_each(arr, callback)
  for i = #arr, 1, -1 do
    callback(arr[i], i)
  end
end
```

This function is linear, the one you showed above is quadratic.
Do you understand my point? Agree?

**Comment by PhilipRoman** [comment]
Ah, I see your point. From the method name I assumed it would do something different. :+1:

**Comment by EvandroLG** [comment]
Done!
